---

- name: Gitlab clean
  block:
    - ansible.builtin.include_tasks: forks.yml
      when: gitlab_clean_forks | bool
      tags:
        - role::gitlab_clean::forks

    - ansible.builtin.include_tasks: mr.yml
      when: gitlab_clean_mr | bool
      tags:
        - role::gitlab_clean::mr
  tags:
    - role::gitlab_clean
