---
# Merge requests cleanup tasks

- block:
    - name: Cleanup forks
      uri:
        url: >-
          {{ gitlab_clean_api_url
             + "/projects/"
             + gitlab_clean_mr_item.project_id | string
             + "/merge_requests/"
             + gitlab_clean_mr_item.iid | string }}
        method: PUT
        headers:
          "Private-Token": "{{ gitlab_fork_token }}"
        body_format: json
        body:
          state_event: close
        return_content: yes
        validate_certs: "{{ gitlab_fork_validate_certs }}"
        status_code: 200
      register: gitlab_clean_mr_result
      changed_when: gitlab_clean_mr_result.status == 202
      loop: >-
        {{ gitlab_mr_fact
           | selectattr("author.username",
                        "search",
                        gitlab_clean_mr_author_username_regex)
           | selectattr("title", "search", gitlab_clean_mr_title_regex)
           | selectattr("created_at",
                        "gitlab_clean_older",
                        gitlab_clean_mr_created_seconds_ago)
           | selectattr("updated_at",
                        "gitlab_clean_older",
                        gitlab_clean_mr_updated_at_seconds_ago)
           | list }}
      loop_control:
        loop_var: gitlab_clean_mr_item
        label: "{{ gitlab_clean_mr_item.references.full }}"
      no_log: "{{ gitlab_clean_no_log | bool }}"
  tags:
    - role::gitlab_clean
    - role::gitlab_clean::mr
